// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA61_95nWpr-t6_90ExOYPXJg0xPjDEDuA',
    appId: '1:623957445835:web:11c849950c613c29021f4e',
    messagingSenderId: '623957445835',
    projectId: 'petukji-stock-utility',
    authDomain: 'petukji-stock-utility.firebaseapp.com',
    storageBucket: 'petukji-stock-utility.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa19p3miMn0BKt4QO5umD9QmWmcg1Y7Ko',
    appId: '1:623957445835:android:85e4fa4ca2d0331d021f4e',
    messagingSenderId: '623957445835',
    projectId: 'petukji-stock-utility',
    storageBucket: 'petukji-stock-utility.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiiSP3yHeju8nvg7vYuXWb9R31S9vKbLc',
    appId: '1:623957445835:ios:b0855b62940f1c00021f4e',
    messagingSenderId: '623957445835',
    projectId: 'petukji-stock-utility',
    storageBucket: 'petukji-stock-utility.appspot.com',
    iosBundleId: 'com.example.petukjiStockUtility',
  );

}